apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-flask-deployment
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: 637423663330.dkr.ecr.ap-northeast-2.amazonaws.com/baggu-vm:nginx-v1.35  # nginx 이미지 버전 변경
      - name: flask
        image: 637423663330.dkr.ecr.ap-northeast-2.amazonaws.com/baggu-vm:flask-v1.35  # flask 이미지 버전 변경
